# encoding: utf-8

require 'rake/testtask'

desc "Run the unit tests"
#task :testunit do |t|
Rake::TestTask.new do |t|
  #t.libs << "test"
  t.test_files = FileList['test_*_unit.rb']
  t.verbose = true
end

#end

task :default => :test

# ____________________________________________________________________
# >>>>>  projet epiculture/ec1   >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>#{{{
# Sources, Infos & Contact : http://www.epiculture.org
# Author: Pierre-Maël Crétinon
# License: GNU GPLv3 ( www.epiculture.org/ec1/LICENSE )
# Copyright: 2010-2012 Pierre-Maël Crétinon
# Sponsor: studio Helianova - http://studio.helianova.com
# ――――――――――――――――――――――――――――――――――――――#}}}
# vim: 
